### PR TITLE
Allow CRUD of Invoices and making Payments

### PR DESCRIPTION
**Pull request by simonwistow**
This is a bit of a big merge to ask so if necessary I can split it up into separate branches. Not least because I saw that you have a Create Invoices branch.

It could probably do with someone else casting their eyes over the fields as well.

There's a fair bit of repeated code to do with validation in models and CRUD in services since I presumed you'd have a plan to pull it all into a base class. I can do that if necessary.

Cheers!

Simon

### CODE REVIEW

**Comment by ruckus** [comment]
Hi Simon, thanks a lot for the contribution. As you probably figured out the code is being actively hacked on so its a moving target and requires cleanup / refactoring. And yes, I just started the invoice creation branch last night and am jamming on that. 

Couple of things:
- in the `CreditCardCharge` class it looks like the `CcExpiteMn` attribute is mis-spelled, it should be `CcExpirMn`, same issue for `CcExpiteYr`
- could you please provide some test specs? Its super easy to mock responses using the `FakeWeb` class. Look at an existing test (such as `spec/quickeebooks/online/services/customer_spec.rb`). Just grab the expected XML from a response, register it with `FakeWeb` and then you can easily test the actual HTTP and response parsing layer.

Thats my first pass, but yeah give the field names another pass. If you implement the tests with expected XML you can catch those field name errors pretty easy.

**Comment by simonwistow** [comment]
Whoops, yup, that's right. 

And yeah, I'll add spec tests

**Comment by ruckus** [comment]
I've just added some specs to the `Windows/Service/Invoice` and `Customer` in the `invoice-creation` branch. I had to update `rspec` in the Gemfile and tweak the paths to the `spec_helper` in each of the above specs to make it run, not sure whats up. If you get caught up in rspec woes than have a look at my changes and maybe they'll help.

**Comment by simonwistow** [comment]
Ok, this should all be updated now. It also includes a bunch of stuff for Payments.

**Comment by ruckus** [comment]
Thanks! I made some tweaks to `master` after I merged.

https://github.com/ruckus/quickeebooks/commit/85aa9cae3c04f4ae60a2fcd06bc767a819b4fcf0

**Pull request merged**
