### PR TITLE
Cleaning up PR #24 - Feature Additions

### PR DESCRIPTION
**Pull request by GeekOnCoffee**

### CODE REVIEW

**Comment by ruckus** [comment]
Thank you so much for the contribution, its really appreciated. Before I can merge in these changes a couple of things:

1) XML generation in the service objects can now be done w/o specifying so much XML by hand, .e.g

```
          xml = <<-XML
          <Add xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" RequestId="#{guid}" xmlns="http://www.intuit.com/sb/cdm/v2">
          <ExternalRealmId>#{self.realm_id}</ExternalRealmId>
          #{xml_node}
          </Add>
          XML
```

can be replaced with:

```
          xml = Quickeebooks::Shared::Service::OperationNode.new.add do |content|
            content << "<ExternalRealmId>#{self.realm_id}</ExternalRealmId>#{xml_node}"
          end
```

See here for an example: https://github.com/ruckus/quickeebooks/blob/master/lib/quickeebooks/windows/service/customer.rb#L24

2) Please provide some tests for these changes.

Thanks again.

**Comment by peterberkenbosch** [comment]
@ruckus what's needed to get this merged? Thanks.

**Comment by ruckus** [comment]
@peterberkenbosch awesome, looks like you made the tweaks for the XML node simplification. Whip up some specs and I can then merge it in. Thanks again!

**Comment by peterberkenbosch** [comment]
thanks @ruckus it was @GeekOnCoffee who did the hard work here :) Will add the specs asap so it can be merged.

**Comment by peterberkenbosch** [comment]
should be good to go @ruckus.

**Comment by ruckus** [comment]
Awesome, thank you! I will release `0.1.21` shortly

**Pull request merged**
