### PR TITLE
Add support for Quickeebooks::Online::Model::JournalEntry

### PR DESCRIPTION
**Pull request by nickhammond**
Added support for journal entries within QBO. I also had to make a few tweaks to the pluralization of the model names, it was just appending an 's' to the model name.

I ended up with this:

<code>self::REST_RESOURCE.underscore.dasherize.pluralize</code>

What I'd really like is a <code>hyphenate</code> method but that doesn't exist. Can you think of a more efficient way to do this? The main use cases are converting JournalEntry -> journal-entries and SalesReceipt -> sales-receipts. So we definitely need <code>pluralize</code> on there to work with models ending in 'y'.

### CODE REVIEW

**Comment by nickhammond** [comment]
I also did a live list, create and update. That's how I found out about the pluralization issue and needed to update that.

I should also note that JournalEntry records require 2 line items, one for the account to credit and the other pointing to the account to debit.

Docs: http://docs.developer.intuit.com/0025_Intuit_Anywhere/0050_Data_Services/v2/0400_QuickBooks_Online/JournalEntry

**Comment by ruckus** [comment]
My concern is that those string methods "underscore", "dasherize" and "pluralize" are in ActiveSupport - which means that Quickeebooks works fine when run inside a Rails app but will fall down outside. And it would be nice not to bring in ActiveSupport as a dependency.

Is it wrong to just override "resource_for_collection" in the Models that have a specific need (e.g. JournalEntry) and return a hard-coded string "journal-entries"?

**Comment by nickhammond** [comment]
The only reason I used those methods is because we are depending on ActiveModel for the validations. ActiveModel depends on ActiveSupport I noticed in the Gemfile.lock

<pre><code>
    activemodel (3.2.12)
      activesupport (= 3.2.12)
      builder (~> 3.0.0)
</code></pre>

Thoughts? Maybe we could just cherry-pick that extension, something like <code>require 'active_support/core_ext/inflections'</code>. I figured though that since it's being installed with ActiveModel we can go ahead and use it, might need to add it to the Gemfile in that case though.

**Comment by ruckus** [comment]
Hmm, you're right, I didn't know ActiveModel depended on ActiveSupport. 

When I included ActiveModel in the first place I did think to myself "seems like an awful big gem to bring in for just validations" and brought it in with a heavy sigh.

Might be a good time to re-evaluate that decision. We could go with a simple gem like this - just provides validations and nothing else: http://rubygems.org/gems/validatable

**Comment by nickhammond** [comment]
It looks like that Gem hasn't been updated in 3 years - https://github.com/jnunemaker/validatable which doesn't mean it won't work. We're currently just including the Validations module on ActiveModel too. I like that the API is pretty much identical though.

**Comment by ruckus** [comment]
hah, yeah I didn't look very hard, thats pretty much the first one I found. I'll dig some more and see what the new hotness is.

But ultimate this would imply:
- we remove ActiveModel in favor of a lean validations library
- we don't include ActiveSupport and find a way to essentially hard-code those special resource strings, possibly by overriding `resource_for_collection` or whatever

**Comment by nickhammond** [comment]
Just tried doing something like <code>require 'active_model/validations'</code> and that depends on ActiveModel::Translation so it's not meant to be cherry picked like ActiveSupport it looks like.

**Comment by nickhammond** [comment]
Did some digging around and my favorite so far is https://github.com/franckverrot/activevalidators. A lot of the gems out there are pretty old or don't have as clean of an interface as ActiveModel. ActiveModel itself was extracted out of AR so that you can use the model related functions so it's meant to be a smaller helper library too. It's sort of meant as a standalone Ruby helper for your Ruby only projects. http://www.rubyinside.com/rails-3-0s-activemodel-how-to-give-ruby-classes-some-activerecord-magic-2937.html

I'm in favor of keeping ActiveModel so we can use ActiveModel::Validations and just cherry picking the pieces of ActiveSupport that we need. I think we could always just hardcode the inflections that we're doing, something like <code>PLURAL_RESTFUL_RESOURCE</code> or <code>REST_RESOURCES</code> like you mentioned.

**Comment by nickhammond** [comment]
Nevermind, that gem depends on activemodel along with a bunch of other dependencies which puts us in the same place.

<pre><code>  s.add_dependency 'rake'          , '>= 0.8.7'
  s.add_dependency 'activemodel'   , '>= 3.0.0'
  s.add_dependency 'phony'         , '~> 1.7.4'
  s.add_dependency 'countries'     , '~> 0.8.2'
  s.add_dependency 'mail'
  s.add_dependency 'date_validator'</code></pre>

**Comment by minimul** [comment]
This is a great thread of discussion and it is important that code quality and dependencies are taken seriously.

However, let's exercise pragmatism too. Refactoring to support validations with a smaller footprint is fine goal but should be its own initiative and shouldn't hold up this important QBO feature.

**Comment by ruckus** [comment]
@minimul fair enough. 

@nickhammond how about just ditching the ActiveSupport string manipulation methods for now and just over-riding the `resource_for_collection` method in the `JournalEntry` model, should just need to be:

``` ruby
class << self
   def resource_for_collection
      self::REST_RESOURCE
   end
end
```

**Comment by nickhammond** [comment]
Reverted the pluralization changes and just manually set 'journal-entries' as the resource for collection, did a quick list check on the live API as well.

**Comment by ruckus** [comment]
Awesome, thank you!

**Pull request merged**
