### PR TITLE
Add in helper methods on the online customer model for phone numbers

### PR DESCRIPTION
**Pull request by nickhammond**
A few minor helper methods similar to the business_address and shipping_address changes that you just made. Next step would be providing setters for those which would be nice.

### CODE REVIEW

**Comment by nickhammond** [comment]
We could actually extract these helper methods into a module and include them on a few different QB models. Customer and Vendor can benefit from all of the helper methods, haven't looked around to see if there are additional models as well.

**Comment by ruckus** [comment]
You're totally right - a common module for Customer & Vendor model address / phone methods is the right call.

I took your code and put it in such a module: a2fa6b9a8f31ca1eabe86bdee8d3ceae6b4f26a8

Thank you!

**Comment by nickhammond** [comment]
Niiiice, this will be handy!

**Comment by nickhammond** [comment]
The Employee model isn't implemented yet but we'll be able to use this on that model too once it's been added. http://docs.developer.intuit.com/0025_Intuit_Anywhere/0050_Data_Services/v2/0400_QuickBooks_Online/Employee

**Pull request closed without merging**
