### PR TITLE
Added to support to return results as Hash instead of ROXML object

### PR DESCRIPTION
**Pull request by cloocher**
- added a flag to return all service results in Hash format
- removed the need to explicitly specify response model since one service always maps to one model
- added specs

### CODE REVIEW

**Comment by ruckus** [comment]
Thanks for the code. I'll probably make some adjustments to this and implement it in the `Windows` flavor as well.

**Comment by ruckus** [comment]
@cloocher Firstly, thank you for taking the time to develop your code and offer it back. Your changes to remove the explicit response model makes total sense. What I am a little unsure about is the Hash format stuff. What are your thoughts on the need for this? Is interacting with Hashes better than Objects?

**Comment by cloocher** [comment]
Correct, I believe interacting with Hashes is much easier than ROXML objects.  Additionally, Hash approve will return all fields from the response, not just those explicitly mapped via ROXML, which might or not include everything.

If you don't think there is much value to providing alternative response format, feel free to ignore it.

**Comment by ruckus** [comment]
Well I can see the value of hashes if your use-case is purely reading info and maybe displaying it. 

The ROXML / Quickebooks objects come into play because you can take an object from a result set, make changes and then immediately hand it off to a service for updating, which you would not be able to do via the Hash route, since at that point you basically have a "dumb hash" instead of a "smart object" - so to speak.

I am going to hold off on bringing in your changes right now.

Actually as I typed this I just came to the idea of actually just implementing a `#to_hash` method which does your stuff - so basically one always get an Object but then has the ability to call `to_hash` if they want a dumb hash. 

That might satisfy everyone... what do you think?

**Comment by cloocher** [comment]
In my case, I only read data, don't have a need to create or update.  For that use case, I don't need ROXML objects at all.  If no one asked for hash results before, what you have is probably good enough for most people - keep it as is.  I am happy to use my branch.

**Pull request closed without merging**
