### PR TITLE
change DATE_TIME_FORMAT in filter to include timezone

### PR DESCRIPTION
**Pull request by seanxiesx**
fix for issue #86

### CODE REVIEW

**Comment by ruckus** [comment]
As you've seen in the commit logs I keep running into issues with this, and I forget the underlying issues why I keep going back and forth. There was a time when I did have `%Z` but then removed it.

**Comment by seanxiesx** [comment]
Yes! I spent some time looking into this.. more details in issue #86 ! (:

My bad I should have attached the pull request to the issue.

**Comment by seanxiesx** [comment]
By the way, there is a separate but somewhat related issue of using timezone in the DateTime filter.

When the timezone is +08:00 (or any other timezone with a plus), Quickbooks throws an unparseable date error.. it looks like this is due to an oauth encoding issue. Double encoding (like the ampersand case) in the escape_filter method of online/service_base.rb fixes the issue for me. Got that by trial and error so spending more time looking at it before I propose a fix.

Might have gone unnoticed if most of the folks using this are based in North America..

**Comment by ruckus** [comment]
Thank you!

**Pull request merged**
