### PR TITLE
fix for bad uri - invoice.id.value instead of invoice.id

### PR DESCRIPTION
**Pull request by theinventor**
Example error I've been getting; 

URI::InvalidURIError: bad URI(is not URI?): https://qbo.sbfinance.intuit.com/resource/invoice/v2/150761966/#Quickeebooks::Online::Model::Id:0x007f86226d3bc0

### CODE REVIEW

**Comment by theinventor** [comment]
I don't suppose we can get a new gem cut with this change in it? That would be awesome

**Comment by ruckus** [comment]
Thanks!

I was actually thinking about this a few days ago - basically just implement `Id#to_s` which returns the value so when its embedded like `#{some_id}` it would just work as expected.

I'll cut a gem in a minute.

**Comment by ruckus** [comment]
Ok - just pushed `0.1.3`

**Comment by cwoolum** [comment]
This needs to be the same for delete

**Pull request merged**
