### PR TITLE
Adding basic support for Windows sorting, pagination, and filtering

### PR DESCRIPTION
**Pull request by MattRogish**
Note, modified spec_helper per
http://blog.mustmodify.com/2010/04/13/rspec-says-undefined-method-should-receive-for-someclass
# Overview

This adds support for Windows API sorting, pagination/chunksize and filtering.
# Sorting

Adds support per https://ipp.developer.intuit.com/0010_Intuit_Partner_Platform/0050_Data_Services/0500_QuickBooks_Windows/0100_Calling_Data_Services/0015_Retrieving_Objects#Sorting
# Pagination/Chunksize

Adds support per
https://ipp.developer.intuit.com/0010_Intuit_Partner_Platform/0050_Data_Services/0500_QuickBooks_Windows/0100_Calling_Data_Services/0015_Retrieving_Objects#Paging

Note the previous Quickeebooks::Windows::ServiceBase#fetch_collection implementation would omit the StartPage and ChunkSize parameters in certain Model#list methods, thus you may see unintended behavior, exhibited as only getting the first 20 results, now that the pagination forces PerPage to be 20 (to match Online API).
# Filtering

Added basic support per https://ipp.developer.intuit.com/0010_Intuit_Partner_Platform/0050_Data_Services/0500_QuickBooks_Windows/0100_Calling_Data_Services/0015_Retrieving_Objects#Filtering

Note that each Model has its own queryable attributes. An example for the InvoiceQuery Attributes:
https://ipp.developer.intuit.com/0010_Intuit_Partner_Platform/0050_Data_Services/0500_QuickBooks_Windows/0600_Object_Reference/Invoice#section_9

This means you cannot query on an arbitrary attribute (e.g. Name > 'foo'). Note that the current implementation will not attempt to whitelist the queryable attributes, so you will receive an Intuit exception if you attempt to query on an un-queryable attribute.

Also, this implementation does not yet support date attributes.

### CODE REVIEW

**Comment by MattRogish** [comment]
In re: pagination, we could set the ChunkSize (per_page in the method call) to be 500 to match the old behavior. That way anyone upgrading wouldn't get unintended consequences, we'd have to maintain the per_page = 500 for a time, then decrease it after enough notice was given. How's that sound?

**Comment by MattRogish** [comment]
Also I see that the CI server is in UTC and I'm in EST. Will fix those tests and push.

**Comment by ruckus** [comment]
Thanks, good stuff! 

I had to pull down your PR and make some adjustments - basically we needed to add in the XML header and the namespace declaration. When I was running the changes against production Intuit it was bitching about the missing namespace:

```
<?xml version="1.0" encoding="utf-8"?>\n<FooQuery xmlns="http://www.intuit.com/sb/cdm/v2">#{res}</FooQuery>
```

**Comment by MattRogish** [comment]
Awesome!!! Thanks!!! What are your thoughts re: ChunkSize? That might bite some people...

**Comment by ruckus** [comment]
Oh yeah I forgot to chime on that... So I don't know, I'm tempted to just keep it the way it is and let people fix their own code. I mean its not a big deal, right? The flip side is that we do maintain the per_page = 500 as you say and then dial it back later. But the question is then - when do we do this? How long must we be backwards-compatible for some unknown number of users?

**Comment by MattRogish** [comment]
Yeah, I'm not sure. It feels like a breaking change (at least, it could cause some confusion) but I agree keeping it for an unknown amount of time is also not good. How best to communicate this? Maybe in the release notes?

**Comment by ruckus** [comment]
Ok, I'd say that if we document this in the release notes and then it let be we will have done our part.

This is not a crazy breaking change in the scheme of things so if it causes some confusion at least its documented in the release notes we should be OK.

**Pull request closed without merging**
